from __future__ import annotations

import inspect
from collections.abc import Callable, Sequence
from functools import partial
from typing import Any, Literal, cast, overload

from anyio import create_task_group

from reactpy.core._event_inspect import inspect_event_handler
from reactpy.types import BaseEventHandler, EventHandlerFunc


@overload
def event(
    function: Callable[..., Any],
    *,
    stop_propagation: bool = ...,
    prevent_default: bool = ...,
    debounce: int | None = ...,
    throttle: int | None = ...,
) -> EventHandler: ...


@overload
def event(
    function: Literal[None] = ...,
    *,
    stop_propagation: bool = ...,
    prevent_default: bool = ...,
    debounce: int | None = ...,
    throttle: int | None = ...,
) -> Callable[[Callable[..., Any]], EventHandler]: ...


def event(
    function: Callable[..., Any] | None = None,
    *,
    stop_propagation: bool = False,
    prevent_default: bool = False,
    debounce: int | None = None,
    throttle: int | None = None,
) -> EventHandler | Callable[[Callable[..., Any]], EventHandler]:
    """A decorator for constructing an :class:`EventHandler`.

    While you're always free to add callbacks by assigning them to an element's attributes

    .. code-block:: python

        element = reactpy.html.button({"onClick": my_callback})

    You may want the ability to prevent the default action associated with the event
    from taking place, or stopping the event from propagating up the DOM. This decorator
    allows you to add that functionality to your callbacks.

    .. code-block:: python

        @event(stop_propagation=True, prevent_default=True)
        def my_callback(*data): ...


        element = reactpy.html.button({"onClick": my_callback})

    Parameters:
        function:
            A function or coroutine responsible for handling the event.
        stop_propagation:
            Block the event from propagating further up the DOM.
        prevent_default:
            Stops the default actional associate with the event from taking place.
        debounce:
            Rate-limit server-→client ``value`` updates for user-input elements.
            See :attr:`BaseEventHandler.debounce`.
        throttle:
            Rate-limit client-→server outgoing events for any element. See
            :attr:`BaseEventHandler.throttle`.
    """

    def setup(function: Callable[..., Any]) -> EventHandler:
        return EventHandler(
            to_event_handler_function(function, positional_args=True),
            stop_propagation,
            prevent_default,
            debounce=debounce,
            throttle=throttle,
        )

    return setup(function) if function is not None else setup


class EventHandler(BaseEventHandler):
    """Turn a function or coroutine into an event handler

    Parameters:
        function:
            The function or coroutine which handles the event.
        stop_propagation:
            Block the event from propagating further up the DOM.
        prevent_default:
            Stops the default action associate with the event from taking place.
        target:
            A unique identifier for this event handler (auto-generated by default)
        debounce:
            Server-→client rate limit (ms) for ``value`` updates on user-input
            elements. See :attr:`BaseEventHandler.debounce`.
        throttle:
            Client-→server rate limit (ms) for outgoing events. See
            :attr:`BaseEventHandler.throttle`.
    """

    def __init__(
        self,
        function: EventHandlerFunc,
        stop_propagation: bool = False,
        prevent_default: bool = False,
        target: str | None = None,
        debounce: int | None = None,
        throttle: int | None = None,
    ) -> None:
        self.function = to_event_handler_function(function, positional_args=False)
        self.prevent_default = prevent_default
        self.stop_propagation = stop_propagation
        self.debounce = debounce
        self.throttle = throttle
        self.target = target

        # Check if our `preventDefault` or `stopPropagation` methods were called
        # by inspecting the function's bytecode
        func_to_inspect = cast(Any, function)
        while hasattr(func_to_inspect, "__wrapped__"):
            func_to_inspect = func_to_inspect.__wrapped__

        if isinstance(func_to_inspect, partial):
            func_to_inspect = func_to_inspect.func

        found_prevent_default, found_stop_propagation, found_debounce = (
            inspect_event_handler(func_to_inspect)
        )

        if found_prevent_default:
            self.prevent_default = True
        if found_stop_propagation:
            self.stop_propagation = True
        if found_debounce is not None:
            self.debounce = found_debounce

    __hash__ = None  # type: ignore

    def __eq__(self, other: object) -> bool:
        undefined = object()
        return not any(
            not attr.startswith("_")
            and not getattr(other, attr, undefined) == getattr(self, attr)
            for attr in (
                "function",
                "prevent_default",
                "stop_propagation",
                "debounce",
                "target",
                "throttle",
            )
        )

    def __repr__(self) -> str:
        public_names = (
            "function",
            "prevent_default",
            "stop_propagation",
            "debounce",
            "target",
            "throttle",
        )
        items = ", ".join([f"{n}={getattr(self, n)!r}" for n in public_names])
        return f"{type(self).__name__}({items})"


def to_event_handler_function(
    function: Callable[..., Any],
    positional_args: bool = True,
) -> EventHandlerFunc:
    """Make a :data:`~reactpy.core.proto.EventHandlerFunc` from a function or coroutine

    Parameters:
        function:
            A function or coroutine accepting a number of positional arguments.
        positional_args:
            Whether to pass the event parameters a positional args or as a list.
    """
    if positional_args:
        if inspect.iscoroutinefunction(function):

            async def wrapper(data: Sequence[Any]) -> None:
                await function(*data)

            cast(Any, wrapper).__wrapped__ = function

        else:

            async def wrapper(data: Sequence[Any]) -> None:
                function(*data)

        cast(Any, wrapper).__wrapped__ = function
        return wrapper
    elif not inspect.iscoroutinefunction(function):

        async def wrapper(data: Sequence[Any]) -> None:
            function(data)

        cast(Any, wrapper).__wrapped__ = function
        return wrapper
    else:
        return function


def merge_event_handlers(
    event_handlers: Sequence[BaseEventHandler],
) -> BaseEventHandler:
    """Merge multiple event handlers into one

    Raises a ValueError if any handlers have conflicting
    :attr:`~reactpy.core.proto.EventHandlerType.stop_propagation`,
    :attr:`~reactpy.core.proto.EventHandlerType.prevent_default`,
    :attr:`~reactpy.core.proto.EventHandlerType.debounce`, or
    :attr:`~reactpy.core.proto.EventHandlerType.throttle` attributes.
    """
    if not event_handlers:
        msg = "No event handlers to merge"
        raise ValueError(msg)
    elif len(event_handlers) == 1:
        return event_handlers[0]

    first_handler = event_handlers[0]

    stop_propagation = first_handler.stop_propagation
    prevent_default = first_handler.prevent_default
    debounce = first_handler.debounce
    throttle = first_handler.throttle
    target = first_handler.target

    for handler in event_handlers:
        if (
            handler.stop_propagation != stop_propagation
            or handler.prevent_default != prevent_default
            or handler.debounce != debounce
            or handler.throttle != throttle
            or handler.target != target
        ):
            msg = (
                "Cannot merge handlers - 'stop_propagation', 'prevent_default', "
                "'debounce', 'throttle' or 'target' mismatch."
            )
            raise ValueError(msg)

    return EventHandler(
        merge_event_handler_funcs([h.function for h in event_handlers]),
        stop_propagation,
        prevent_default,
        target,
        debounce,
        throttle,
    )


def merge_event_handler_funcs(
    functions: Sequence[EventHandlerFunc],
) -> EventHandlerFunc:
    """Make one event handler function from many"""
    if not functions:
        msg = "No event handler functions to merge"
        raise ValueError(msg)
    elif len(functions) == 1:
        return functions[0]

    async def await_all_event_handlers(data: Sequence[Any]) -> None:
        async with create_task_group() as group:
            for func in functions:
                group.start_soon(func, data)

    return await_all_event_handlers
